### ISSUE TITLE
todo js logik

### ISSUE THREAD

**Issue by jkat74** [jkat74/annat_repo#8]
Skapa följande:
- [ ] Todo-item js objekt med namn, datum, prioritet (låg, medel ,hög)
- [x]  Lagra todo-items i array 
- [ ] Spara Array i localstorage

Repo: https://github.com/jkat74/annat_repo.git
